# Generated by Django 2.2.4 on 2019-08-11 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShopInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmember',
            name='role',
            field=models.CharField(choices=[('sender', 'Sender'), ('editor', 'Editor'), ('admin', 'Admin')], default='sender', max_length=16),
        ),
        migrations.AddField(
            model_name='shopmember',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ShopInterface.Shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopmember',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
