# Generated by Django 2.2.4 on 2019-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Subscription'),
        ),
    ]
